# Generated by Django 2.2.10 on 2020-06-14 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('Secuencia', models.CharField(default=0, max_length=200)),
                ('Correo', models.EmailField(max_length=254)),
                ('idSecuencia', models.IntegerField(default=0)),
                ('Nombre', models.CharField(default=0, max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Swiss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSwissModel', models.CharField(max_length=200)),
                ('SecIdRes', models.CharField(max_length=200)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia')),
            ],
        ),
        migrations.CreateModel(
            name='Raptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSecSsb', models.CharField(max_length=200)),
                ('idSecAcc', models.CharField(max_length=200)),
                ('idSecDisc', models.CharField(max_length=200)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia')),
            ],
        ),
        migrations.CreateModel(
            name='InterPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSeqFamilia', models.CharField(max_length=200)),
                ('idSeqDominio', models.CharField(max_length=200)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia')),
            ],
        ),
        migrations.CreateModel(
            name='Clustal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSecPhylo', models.CharField(max_length=200)),
                ('idSecMatriz', models.CharField(max_length=200)),
                ('idSecTree', models.CharField(max_length=200)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia')),
            ],
        ),
        migrations.CreateModel(
            name='Cath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secIdRes', models.CharField(max_length=200)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia')),
            ],
        ),
        migrations.CreateModel(
            name='Blast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBlast', models.CharField(max_length=100)),
                ('Secuencia', models.CharField(max_length=200)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia')),
            ],
        ),
    ]
