# Generated by Django 2.2.10 on 2020-05-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuencia',
            name='Correo',
            field=models.EmailField(max_length=254),
        ),
    ]
