# Generated by Django 2.2.10 on 2020-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0002_auto_20200527_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuencia',
            name='nombre',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
