# Generated by Django 2.2.10 on 2020-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0003_secuencia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secuencia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='secuencia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='secuencia',
            name='Nombre',
            field=models.CharField(default=0, max_length=250, primary_key=True, serialize=False),
        ),
    ]
