# Generated by Django 2.2.10 on 2020-06-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0004_auto_20200602_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='blast',
            name='nombre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia'),
        ),
    ]
