# Generated by Django 2.2.10 on 2020-06-02 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0005_blast_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cath',
            name='nombre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia'),
        ),
        migrations.AddField(
            model_name='clustal',
            name='nombre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia'),
        ),
        migrations.AddField(
            model_name='interpro',
            name='nombre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia'),
        ),
        migrations.AddField(
            model_name='raptor',
            name='nombre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia'),
        ),
        migrations.AddField(
            model_name='swiss',
            name='nombre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TT.Secuencia'),
        ),
    ]
